# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &Org${NAME}
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: Org${NAME}MSP

        # ID to load the MSP definition as
        ID: Org${NAME}MSP

        MSPDir: ../organizations/peerOrganizations/org${NAME}.example.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org${NAME}MSP.admin', 'Org${NAME}MSP.peer', 'Org${NAME}MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org${NAME}MSP.admin', 'Org${NAME}MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org${NAME}MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Org${NAME}MSP.peer')"
