  peer0.${DOMAIN}:
    container_name: peer0.${DOMAIN}
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.${DOMAIN}
      - CORE_PEER_ADDRESS=peer0.${DOMAIN}:${PEER_PORT}
      - CORE_PEER_LISTENADDRESS=0.0.0.0:${PEER_PORT}
      - CORE_PEER_CHAINCODEADDRESS=peer0.${DOMAIN}:${PEER_CHAINCODE_PORT}
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:${PEER_CHAINCODE_PORT}
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.${DOMAIN}:${PEER_PORT}
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.${DOMAIN}:${PEER_PORT}
      - CORE_PEER_LOCALMSPID=Org${NAME}MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=peer0.${DOMAIN}:${PEER_OPERATION_PORT}
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0org${NAME}"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
        - ../organizations/peerOrganizations/${DOMAIN}/peers/peer0.${DOMAIN}:/etc/hyperledger/fabric
        - peer0.${DOMAIN}:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - ${PEER_PORT}:${PEER_PORT}
      - ${PEER_OPERATION_PORT}:${PEER_OPERATION_PORT}
    networks:
      - test

